HospitalWeb/HospitalWeb.Mvc/Controllers/StatisticsController.cs
using HospitalWeb.Mvc.Filters.Builders.Implementations;
using HospitalWeb.Mvc.Filters.Models.DTO;
using HospitalWeb.Mvc.ViewModels.Statistics;
using HospitalWeb.Mvc.Clients.Implementations;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HospitalWeb.Mvc.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly ILogger<StatisticsController> _logger;
        private readonly ApiUnitOfWork _api;

        public StatisticsController(ILogger<StatisticsController> logger, ApiUnitOfWork api)
        {
            _logger = logger;
            _api = api;
        }

        [HttpGet]
        public IActionResult Index(
            int? locality = null,
            DateTime? fromDate = null,
            DateTime? toDate = null)
        {
            var builder = new AppointmentsViewModelBuilder(_api, state: 5, locality: locality, fromTime: fromDate, toTime: toDate, pageSize: int.MaxValue);
            var director = new ViewModelBuilderDirector();
            director.MakeViewModel(builder);
            var viewModel = builder.GetViewModel(); 

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult IndexSpeed(
            int? locality = null,
            DateTime? fromDate = null,
            DateTime? toDate = null)
        {
            var start = DateTime.Now;

            var builder = new AppointmentsViewModelBuilder(_api, state: 5, locality: locality, fromTime: fromDate, toTime: toDate, pageSize: int.MaxValue);
            var director = new ViewModelBuilderDirector();
            director.MakeViewModel(builder);
            var viewModel = builder.GetViewModel();

            var end = DateTime.Now;

            return Content($"start: {start}, end: {end}, dif: {(end - start).TotalSeconds}");
        }

        [HttpGet]
        public async Task<IActionResult> TestAwait(int? locality = null,
            DateTime? fromDate = null,
            DateTime? toDate = null)
        {
            var start = DateTime.Now;

            var httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("https://yigalhospitalapi.azurewebsites.net/api/");
            var response = await httpClient.GetAsync("Appointments/details");
            var appointments = await response.Content.ReadAsByteArrayAsync();

            var end = DateTime.Now;

            return Content($"start: {start}, end: {end}, dif: {(end - start).TotalSeconds}");
        }

        [HttpGet]
        public IActionResult TestResult(int? locality = null,
            DateTime? fromDate = null,
            DateTime? toDate = null)
        {
            var start = DateTime.Now;

            var httpClient = new HttpClient();
            httpClient.BaseAddress = new Uri("https://yigalhospitalapi.azurewebsites.net/api/");
            var response = httpClient.GetAsync("Appointments/details").Result;
            var appointments = response.Content.ReadAsByteArrayAsync().Result;

            var end = DateTime.Now;

            return Content($"start: {start}, end: {end}, dif: {(end - start).TotalSeconds}");
        }

        [HttpPost]
        public IActionResult Attendance([FromBody] List<AppointmentDTO> appointments)
        {
            var model = appointments
                .GroupBy(a => a.AppointmentDate.Date)
                .Select(g => new AttendanceStatViewModel { VisitDate = g.Key, VisitsCount = g.Count() })
                .ToList();

            return Json(model);
        }

        [HttpPost]
        public IActionResult Diagnosis([FromBody] List<AppointmentDTO> appointments)
        {
            var rawModel = appointments
                .GroupBy(a => a.Diagnosis)
                .Select(g => new DiagnosesStatViewModel { Label = g.Key, Count = g.Count() })
                .ToList();

            var model = rawModel
                .Take(10)
                .ToList();

            if (rawModel.Count > 10)
            {
                var other = new DiagnosesStatViewModel
                {
                    Label = "Other",
                    Count = rawModel
                        .Skip(10)
                        .Sum(m => m.Count)
                };

                model.Add(other);
            }

            return Json(model);
        }

        [HttpPost]
        public IActionResult Hospital([FromBody] List<AppointmentDTO> appointments)
        {
            var rawModel = appointments
                .GroupBy(a => a.Hospital)
                .Select(g => new HospitalStatViewModel { Label = g.Key, Count = g.Count() })
                .OrderBy(m => m.Count)
                .ToList();

            var model = rawModel
                .Take(10)
                .ToList();

            if (rawModel.Count > 10)
            {
                var other = new HospitalStatViewModel
                {
                    Label = "Other",
                    Count = rawModel
                        .Skip(10)
                        .Sum(m => m.Count)
                };

                model.Add(other);
            }

            return Json(model);
        }

        [HttpPost]
        public IActionResult Specialty([FromBody] List<AppointmentDTO> appointments)
        {
            var rawModel = appointments
                .GroupBy(a => a.DoctorSpecialty)
                .Select(g => new SpecialtyStatViewModel { Label = g.Key, Count = g.Count() })
                .ToList();

            var model = rawModel
                .Take(5)
                .ToList();

            if (rawModel.Count > 5)
            {
                var other = new SpecialtyStatViewModel
                {
                    Label = "Other",
                    Count = rawModel
                        .Skip(5)
                        .Sum(m => m.Count)
                };

                model.Add(other);
            }

            return Json(model);
        }
    }
}

HospitalWeb/HospitalWeb.Mvc/Views/Shared/_AccountLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewBag.Title</title>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />     	
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" /> 
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" /> 
    </head>
    <body class="bg-light">
       <main>
           <div class="container">
               @RenderBody()
           </div>
       </main>
       <script src="~/js/site.js"></script>
       <script src="~/lib/jquery/jquery.min.js"></script>
       <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
       <script src="~/lib/jQuery-Validation/jquery.validate.min.js"></script>
       <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
       @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

HospitalWeb/HospitalWeb.Mvc/Views/Shared/_FooterPartial.cshtml
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<section class="border-top mt-5">
    <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
            <div class="col-sm-4 mx-auto">
                <h6 class="text-uppercase fw-bold mb-4">
                    <i class="fa-solid fa-truck-medical me-3 text-secondary"></i>Hospital
                </h6>
                <p>
                    @SharedLocalizer["FooterText"]
                </p>
            </div>
            <div class="col-sm-4 mx-auto">
                <h6 class="text-uppercase fw-bold mb-4">
                    @SharedLocalizer["Info"]
                </h6>
                <p>
                    <a asp-controller="Home" asp-action="Index" class="text-reset">@SharedLocalizer["Home"]</a>
                </p>
                <p>
                    <a asp-controller="Home" asp-action="About" class="text-reset">@SharedLocalizer["About"]</a>
                </p>
                <p>
                    <a asp-controller="Home" asp-action="Privacy" class="text-reset">@SharedLocalizer["Privacy"]</a>
                </p>
            </div>
            <div class="col-sm-4 mx-auto">
                <h6 class="text-uppercase fw-bold mb-4">@SharedLocalizer["Contact"]</h6>
                <p>
                    <a href="https://github.com/ihornekhaienko" class="text-reset">
                        <i class="fa-brands fa-github"></i>
                        Git
                    </a>
                </p>
                <p>
                    <a href="https://t.me/igornekhaienko" class="text-reset">
                        <i class="fa-brands fa-telegram"></i>
                        Telegram
                    </a>
                </p>
                <p>
                    <a href="mailto:ihornekhaienko@gmail.com" class="text-reset">
                        <i class="fas fa-envelope"></i>
                        ihornekhaienko@gmail.com
                    </a>
                </p>
                <p>
                    <a href="tel:+0500558375" class="text-reset">
                        <i class="fa-solid fa-phone"></i>
                        + 38 (050) 055 83 75
                    </a>
                </p>
            </div>
        </div>
    </div>
</section>

<div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
    © 2022 Copyright:
    <a class="text-reset fw-bold" href="https://github.com/ihornekhaienko">Ihor Nekhaienko</a>
</div>

HospitalWeb/HospitalWeb.Mvc/Views/Shared/_Layout.cshtml
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewBag.Title</title>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />     	
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" /> 
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" /> 
        <link rel="stylesheet" href="~/css/cardjs.min.css"/>
    </head>
    <body class="d-flex flex-column min-vh-100">
        <header>
            <nav class="navbar navbar-expand-md fixed-top bg-sea-green">
                <div class="container-fluid">
                    <a class="navbar-brand white" asp-controller="Home" asp-action="Index">Hospital</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">
                                    <i class="fa-solid fa-house"></i>
                                    @SharedLocalizer["Home"]
                                </a>
                            </li>
                            <partial name="_RolePartial" />
                        </ul>
                        <ul class="navbar-nav">
                            <partial name="_LoginPartial" />
                            <partial name="_LocalPartial" />
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <main role="main" class="container main mb-10">
            @RenderBody()

            <section>
                <partial name="_SupportPartial" />
            </section>
        </main>
        

        <footer class="mt-auto text-center text-lg-start bg-white text-muted">
            <partial name="_FooterPartial" />
        </footer>

        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/jQuery-Validation/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
        <script src="~/lib/microsoft/signalr/dist/browser/signalr.min.js"></script>
        <script src="~/lib/plotly.js/plotly.min.js"></script>
        <script src="~/lib/qrcodejs/qrcode.min.js"></script>
        <script src="~/js/cardjs/card-js.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

HospitalWeb/HospitalWeb.Mvc/Views/Shared/_LocalPartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
 
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.Name })
        .ToList();
}

<form method="post" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path">
    <li class="nav-item">
        <select name="culture" onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems" class="bg-sea-green nav-link" style="border:none;"></select>
    </li>
</form>

HospitalWeb/HospitalWeb.Mvc/Views/Shared/_RolePartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

@if (SignInManager.IsSignedIn(User))
{
    if (User.IsInRole("Admin"))
    {
        <li class="nav-item">
            <div class="dropdown">
                <button class="btn btn-sea-green nav-btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-users"></i>
                    @SharedLocalizer["Administration"]
                </button>
                <ul class="dropdown-menu bg-sea-green">
                    <li>
                        <a class="nav-link bg-sea-green" asp-controller="Administration" asp-action="Admins">
                            <i class="fa-solid fa-hammer"></i>
                            @SharedLocalizer["Admins"]
                        </a>
                    </li>
                    <li>
                        <a class="nav-link bg-sea-green" asp-controller="Administration" asp-action="Doctors">
                            <i class="fa-solid fa-stethoscope"></i>
                            @SharedLocalizer["Doctors"]
                        </a>
                    </li>
                    <li>
                        <a class="nav-link bg-sea-green" asp-controller="Administration" asp-action="Patients">
                            <i class="fa-solid fa-hospital-user"></i>
                            @SharedLocalizer["Patients"]
                        </a>
                    </li>
                    <li>
                        <a class="nav-link bg-sea-green" asp-controller="Administration" asp-action="Hospitals">
                            <i class="fa-solid fa-hospital"></i>
                            @SharedLocalizer["Hospitals"]
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    }
    else if (User.IsInRole("Doctor"))
    {
        <li class="nav-item">
            <a class="nav-link bg-sea-green" asp-controller="Appointments" asp-action="Today">
                <i class="fa-solid fa-calendar-check"></i>
                @SharedLocalizer["Appointments"]
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-sea-green" asp-controller="Appointments" asp-action="History">
                <i class="fa-solid fa-clock-rotate-left"></i>
                @SharedLocalizer["History"]
            </a>
        </li>
    }
    else if (User.IsInRole("Patient"))
    {
        <li class="nav-item">
            <a class="nav-link bg-sea-green" asp-controller="Hospitals" asp-action="Search">
                <i class="fa-solid fa-hospital"></i>
                @SharedLocalizer["SearchHospitals"]
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-sea-green" asp-controller="Doctors" asp-action="Search">
                <i class="fa-solid fa-magnifying-glass"></i>
                @SharedLocalizer["SearchDoctors"]
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link bg-sea-green" asp-controller="Treatment" asp-action="History">
                <i class="fa-solid fa-file-medical"></i>
                @SharedLocalizer["Treatment"]
            </a>
        </li>
    }
    <li class="nav-item">
        <a class="nav-link" asp-controller="Statistics" asp-action="Index">
            <i class="fa-solid fa-chart-simple"></i>
           @SharedLocalizer["Statistics"]
        </a>
    </li> 
    <li class="nav-item">
        <a class="nav-link" asp-controller="Manage" asp-action="Profile"
        data-bs-toggle="popover" data-bs-trigger="hover" data-bs-content-id="notifications" data-bs-placement="bottom">
            <i class="fa-solid fa-user"></i>
            @SharedLocalizer["Profile"]
            <span id="notifications-count" class="badge badge-light" onclick="removeNotification()"></span>
            <div id="notifications" class="d-none">
            </div>
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link bg-sea-green" asp-controller="Hospitals" asp-action="Search">
            <i class="fa-solid fa-hospital"></i>
            @SharedLocalizer["SearchHospitals"]
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link bg-sea-green" asp-controller="Doctors" asp-action="Search">
            <i class="fa-solid fa-magnifying-glass"></i>
            @SharedLocalizer["SearchDoctors"]
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-controller="Statistics" asp-action="Index">
            <i class="fa-solid fa-chart-simple"></i>
            @SharedLocalizer["Statistics"]
        </a>
    </li>
}

HospitalWeb/HospitalWeb.Mvc/Views/Shared/_SupportPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> signInManager
@inject UserManager<AppUser> userManager


@if (signInManager.IsSignedIn(User))
{
    if (User.IsInRole("Admin"))
    {
        <div class="container">
            <div class="chatbox">
                <button class="chat-btn" id="chat-btn"> 
                    <i class="fa-solid fa-comments"></i>
                </button>
                <div class="chat-popup">
                    <button class="chat-badge chat-user d-none" id="chat-all-users">
                        <i class="fa-solid fa-users"></i>
                    </button>

                    <div class="chat-list chat-area" id="chat-list">
                    </div>

                    <div class="chat-area chat-user d-none" id="chat-user">
                    </div>

                    <div class="input-area chat-user d-none">
                        <input type="hidden" id="chat-user-id">
                        <input type="hidden" id="chat-user-name">
                        <input type="text" id="message-text">
                        <button class="chat-send" id="admin-send"> 
                            <i class="fa-solid fa-paper-plane"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }

    if (User.IsInRole("Patient") || User.IsInRole("Doctor"))
    {
        var user = await userManager.FindByEmailAsync(User.Identity.Name);
        var userId = user.Id;
        var name = user.ToString();

        <div class="container">
            <div class="chatbox">
                <button class="chat-btn" id="chat-btn"> 
                    <i class="fa-solid fa-comments"></i>
                </button>

                <div class="chat-popup">
                    <div class="chat-area" id="msg-list">
                    </div>

                    <div class="input-area">
                        <input type="hidden" id="chat-user-id" value="@userId">
                        <input type="hidden" id="chat-user-name" value="@name">
                        <input type="text" id="message-text">
                        <button class="chat-send" id="user-send" > 
                            <i class="fa-solid fa-paper-plane"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
}
else 
{
    <div class="container">
            <div class="chatbox">
                <button class="chat-btn" id="chat-btn"> 
                    <i class="fa-solid fa-comments"></i>
                </button>

                <div class="chat-popup">
                    <div class="chat-area" id="msg-list">
                    </div>

                    <div class="input-area">
                        <input type="hidden" id="chat-guest-id">
                        <input type="text" id="message-text">
                        <button class="chat-send" id="guest-send" > 
                            <i class="fa-solid fa-paper-plane"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
}