HospitalWeb/HospitalWeb.Mvc/Controllers/HomeController.cs
using HospitalWeb.Mvc.Clients.Implementations;
using HospitalWeb.Domain.Entities.Identity;
using HospitalWeb.Mvc.Filters.Builders.Implementations;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace HospitalWeb.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApiUnitOfWork _api;
        private readonly SignInManager<AppUser> _signInManager;

        public HomeController(
            ILogger<HomeController> logger,
            ApiUnitOfWork api,
            SignInManager<AppUser> signInManager)
        {
            _logger = logger;
            _api = api;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string searchString)
        {
            return RedirectToAction("Search", "Doctors", new { searchString = searchString });
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        [HttpPost]
        public IActionResult LoadLatestNotifications()
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return null;
            }

            var response = _api.AppUsers.Get(User.Identity.Name, null, null);

            if (!response.IsSuccessStatusCode)
            {
                var statusCode = response.StatusCode;
                var message = _api.Patients.ReadError<string>(response);

                return RedirectToAction("Http", "Error", new { statusCode = statusCode, message = message });
            }

            var patient = _api.Patients.Read(response);

            var builder = new NotificationsViewModelBuilder(_api, 1, patient.Id, isRead: false, pageSize: 5);
            var director = new ViewModelBuilderDirector();
            director.MakeViewModel(builder);
            var model = builder.GetViewModel();

            return Json(model.Notifications);
        }
    }
}

HospitalWeb/HospitalWeb.Mvc/Controllers/HospitalsController.cs
using HospitalWeb.Mvc.Filters.Builders.Implementations;
using HospitalWeb.Mvc.Services.Interfaces;
using HospitalWeb.Mvc.ViewModels.Error;
using HospitalWeb.Mvc.Clients.Implementations;
using HospitalWeb.Mvc.Models.SortStates;
using Microsoft.AspNetCore.Mvc;

namespace HospitalWeb.Mvc.Controllers
{
    public class HospitalsController : Controller
    {
        private readonly ILogger<HospitalsController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly ApiUnitOfWork _api;
        private readonly IFileManager _fileManager;

        public HospitalsController(
            ILogger<HospitalsController> logger, 
            IWebHostEnvironment environment, 
            ApiUnitOfWork api, 
            IFileManager fileManager)
        {
            _logger = logger;
            _environment = environment;
            _api = api;
            _fileManager = fileManager;
        }

        [HttpGet]
        public async Task<IActionResult> Search(
            string searchString,
            int? locality,
            int page = 1,
            HospitalSortState sortOrder = HospitalSortState.Id)
        {
            try
            {
                ViewBag.Image = await _fileManager.GetBytes(Path.Combine(_environment.WebRootPath, "files/images/hospital-icon.png"));

                var builder = new HospitalsViewModelBuilder(_api, page, searchString, sortOrder, locality);
                var director = new ViewModelBuilderDirector();
                director.MakeViewModel(builder);
                var viewModel = builder.GetViewModel();

                return View(viewModel);
            }
            catch (Exception err)
            {
                _logger.LogError($"Error in HospitalsController.Search.Get: {err.Message}");
                _logger.LogError($"Inner exception:\n{err.InnerException}");
                _logger.LogTrace(err.StackTrace);

                return RedirectToAction("Index", "Error", new ErrorViewModel { Message = err.Message });
            }
        }
    }
}

HospitalWeb/HospitalWeb.Mvc/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@{
    ViewBag.Title = "HospitalWeb";
}

@if (SignInManager.IsSignedIn(User))
{
    if (User.IsInRole("Admin"))
    {
        <partial name="_AdminPartial" />
    }
    else if (User.IsInRole("Doctor"))
    {
        <partial name="_DoctorPartial" />
    }
    else if (User.IsInRole("Patient"))
    {
        <partial name="_DefaultPartial" />
    }
}
else
{
    <partial name="_DefaultPartial" />
}

HospitalWeb/HospitalWeb.Mvc/Views/Home/_AdminPartial.cshtml
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<div class="container">
    <div class="row mt-5">
        <div class="col">
            <div class="card mx-auto h-100" style="width:250px;">
                <img src="./files/images/admin.png" class="card-img-top photo mt-1" alt="Admins">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["ManageAdmins"]</h4>
                    <a asp-controller="Administration" asp-action="Admins" class="btn btn-primary mt-auto">@SharedLocalizer["Manage"]</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto h-100" style="width:250px;">
                <img src="./files/images/doctor.png" class="card-img-top photo mt-1" alt="Doctors">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["ManageDoctors"]</h4>
                    <a asp-controller="Administration" asp-action="Doctors" class="btn btn-primary mt-auto">@SharedLocalizer["Manage"]</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto h-100" style="width:250px;">
                <img src="./files/images/patient.jpg" class="card-img-top photo mt-1" alt="Patients">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["ManagePatients"]</h4>
                    <a asp-controller="Administration" asp-action="Patients" class="btn btn-primary mt-auto">@SharedLocalizer["Manage"]</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto h-100" style="width:250px;">
                <img src="./files/images/hospital.png" class="card-img-top photo mt-1" alt="Statistics">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["LookForStatistics"]</h4>
                    <a asp-controller="Stat" asp-action="Index" class="btn btn-primary mt-auto">@SharedLocalizer["Show"]</a>
                </div>
            </div>
        </div>
    </div>
</div>

HospitalWeb/HospitalWeb.Mvc/Views/Home/_DefaultPartial.cshtml
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<div class="container">
    <div class="row mt-5">
    <div class="col-sm-6 mx-auto text-center">
        <h4>@SharedLocalizer["SearchDoctorsAd"]</h4>
    </div>
    </div>
    <div class="row mt-2">
         <div class="col-sm-6 mx-auto text-center">
            <h6>@SharedLocalizer["MakeAppointment"]</h6>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-6 mx-auto text-center">
             <form method="post">
                <input class="search-input" name="searchString" placeholder="@SharedLocalizer["EnterDoctor"]" style="min-width:300px;"/>
                <span class="input-group-btn input-space">
                    <button type="submit" class="btn btn-success btn-sm">
                        @SharedLocalizer["Search"]
                    </button>
                </span>
             </form>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <div class="card mx-auto h-100" style="width:300px;">
                <img src="./files/images/doctor.png" class="card-img-top photo mt-1" alt="Find doctor">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["FindDoctor"]</h4>
                    <a asp-controller="Doctors" asp-action="Search" class="btn btn-primary mt-auto">@SharedLocalizer["Find"]</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto h-100" style="width:300px;">
                <img src="./files/images/hospital.png" class="card-img-top photo mt-1" alt="Find hospital">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["FindHospital"]</h4>
                    <a asp-controller="Hospitals" asp-action="Search" class="btn btn-primary mt-auto">@SharedLocalizer["Find"]</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto h-100" style="width:300px;">
                <img src="./files/images/stats.jpg" class="card-img-top photo mt-1" alt="Show stats">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["LookForStatistics"]</h4>
                    <a asp-controller="Stat" asp-action="Index" class="btn btn-primary mt-auto">@SharedLocalizer["Show"]</a>
                </div>
            </div>
        </div>
    </div>
</div>

HospitalWeb/HospitalWeb.Mvc/Views/Home/_DoctorPartial.cshtml
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<div class="container">
    <div class="row mt-4">
        <div class="col">
            <div class="card mx-auto h-100" style="width:300px;">
                <img src="./files/images/appointment.png" class="card-img-top photo mt-1" alt="Appointments">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["ManageAppointments"]</h4>
                    <a asp-controller="Appointments" asp-action="Index" class="btn btn-primary mt-auto">@SharedLocalizer["Manage"]</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto h-100" style="width:300px;">
                <img src="./files/images/history.png" class="card-img-top photo mt-1 ml-1 mr-1" alt="History">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["ShowHistory"]</h4>
                    <a asp-controller="Appointments" asp-action="History" class="btn btn-primary mt-auto">@SharedLocalizer["Show"]</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mx-auto h-100" style="width:300px;">
                <img src="./files/images/stats.jpg" class="card-img-top photo mt-1" alt="Show stats">
                <div class="card-body text-center d-flex flex-column">
                    <h4 class="card-title">@SharedLocalizer["LookForStatistics"]</h4>
                    <a asp-controller="Stat" asp-action="Index" class="btn btn-primary mt-auto">@SharedLocalizer["Show"]</a>
                </div>
            </div>
        </div>
    </div>
</div>